version: '3'

networks:
  tictactoeapi-dev:
    driver: bridge

services:
  dockerapp:
    image: tictactoe:latest
    depends_on:
      - "postgres_image"
    build:
      dockerfile: TicTacToe\Dockerfile
    ports:
      - "3500:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=tictactoe;username=postgres;password=postgres"
    networks:
      - tictactoeapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tictactoe"
    networks:
      - tictactoeapi-dev

